# Generated by Django 3.0.8 on 2020-07-25 11:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dezzex_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='image',
            field=models.ImageField(default='', null=True, upload_to='upload/product/'),
        ),
        migrations.AddField(
            model_name='customer',
            name='registration_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
